version: '3'
services:

  api:
    image: watcharaphat/tm-benchmark-api:latest
    environment:
     - TENDERMINT_IP=localhost
     - TENDERMINT_PORT=45000
     - SERVER_PORT=8000
     - DISCOVERY_HOSTNAME=${DISCOVERY_HOSTNAME:-controller}
     - DISCOVERY_PORT=3000
    ports:
      - 8000:8000
    network_mode: host
    depends_on:
      - tm-node

  # secondary nodes
  tm-node:
    image: watcharaphat/tendermint:latest
    environment:
      - TM_RPC_PORT=${TM_RPC_PORT:-45000}
      - SEED_HOSTNAME=${GENESIS:-genesis0}
    command:
      - secondary
      - --p2p.laddr=tcp://0.0.0.0:${TM_P2P_PORT:-47000}
      - --rpc.laddr=tcp://0.0.0.0:${TM_RPC_PORT:-45000}
      - --proxy_app=tcp://localhost:${ABCI_PORT:-46000}
    ports:
      - 45000:${TM_RPC_PORT:-45000}
      - 47000:${TM_P2P_PORT:-47000}
    network_mode: host

  abci:
    image: watcharaphat/abci:latest
    command: ["tcp://0.0.0.0:${ABCI_PORT:-46000}"]
    environment:
     - DISCOVERY_HOSTNAME=controller
     - DISCOVERY_PORT=3000
    ports:
      - 8100:8100
    network_mode: host
